version: '3.8'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: social_media
    ports:
      - "3305:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: